export class Flight {

 "itinerary_id":any;
 "type":any;
 "airline":any;
 "airline_code":any;
 "flight_number":any;
 "dep_airport":any;
 "dep_city":any;
 "dep_city_code":any;
 "dep_country":any;
 "dep_latitude":any;
 "dep_longitude":any;
 "dep_terminal":any;
 "dep_iata":any;
 "dep_region_name":any;
 "dep_time_zone":any;
 "dep_date":any;
 "dep_time":any;
 "arr_airport":any;
 "arr_city":any;
 "arr_city_code":any;
 "arr_country":any;
 "arr_latitude":any;
 "arr_longitude":any;
 "arr_terminal":any;
 "arr_iata":any;
 "arr_region_name":any;
    

}
export class PstFlightData  {
                     "itinerary_id":any;
                     "type":any;
                     "airline":"";
                     "airline_code":"";
                     "flight_number":"";
                     "dep_airport":"";
                     "dep_city":"";
                     "dep_city_code":"";
                     "dep_country":"";
                     "dep_latitude":"";
                     "dep_longitude":"";
                     "dep_terminal":"";
                     "dep_iata":"";
                     "dep_region_name":"";
                     "dep_time_zone":"";
                     "dep_date":"";
                     "dep_time":"";
                     "arr_airport":"";
                     "arr_city":"";
                     "arr_city_code":"";
                     "arr_country":"";
                     "arr_latitude":"";
                     "arr_longitude":"";
                     "arr_terminal":"";
                     "arr_iata":"";
                     "arr_region_name":"";
                     "arr_date":"";
                     "arr_time":"";
                     "dep_date_time":"";
                     "arr_date_time":"";
                   }

export class Flights{
"id":any;
    "itinerary_id" : any;
    
      "departure_title":any;
        "dep_fight_name":any;
        "dep_fight_number":any;
        "from_airport_name":any;
        "from_poi_name":any;
        "from_city_id":any;
        "from_state_id":any;
        "from_country":any;
        "from_place_id":any;
        "from_latitude":any;
        "from_longitude":any;
        "from_address":any;
        "to_fight_name":any;
        "to_fight_number":any;
        "to_airport_name":any;
        "to_poi_name":any;
        "to_city_id":any;
        "to_state_id":any;
        "to_country":any;
        "to_place_id":any;
        "to_latitude":any;
        "to_longitude":any;
        "to_address":any;
            "arrival_title":any;
            "arr_fight_name":any;
            "arr_fight_number":any;
            "arr_from_airport_name":any;
            "arr_from_poi_name":any;
            "arr_from_city_id":any;
            "arr_from_state_id":any;
            "arr_from_country":any;
            "arr_from_place_id":any;
            "arr_from_latitude":any;
            "arr_from_longitude":any;
            "arr_from_address":any;
            "arr_to_fight_name":any;
            "arr_to_fight_number":any;
            "arr_to_airport_name":any;
            "arr_to_poi_name":any;
            "arr_to_city_id":any;
            "arr_to_state_id":any;
            "arr_to_country":any;
            "arr_to_place_id":any;
            "arr_to_latitude":any;
            "arr_to_longitude":any;
            "arr_to_address":any;
}

// this.editableFlight.dep_airport=flightData.dep_airport;
// this.editableFlight.arr_airport=flightData.arr_airport;
// this.editableFlight.airline=flightData.airline;
// this.editableFlight.arr_date_time=flightData.arr_date_time;
// this.editableFlight.dep_date_time=flightData.dep_date_time;
// this.editableFlight.arr_time=flightData.arr_time;
// this.editableFlight.arr_date=flightData.arr_date;
// this.editableFlight.arr_region_name=flightData.arr_region_name;
// this.editableFlight.arr_iata=flightData.arr_iata;
// this.editableFlight.arr_terminal=flightData.arr_terminal;
// this.editableFlight.arr_longitude=flightData.arr_longitude;
// this.editableFlight.arr_latitude=flightData.arr_latitude;
// this.editableFlight.arr_country=flightData.arr_country;
// this.editableFlight.arr_city_code=flightData.arr_city_code; 
// this.editableFlight.arr_city=flightData.arr_city;
// this.editableFlight.dep_time=flightData.dep_time;
// this.editableFlight.dep_date=flightData.dep_date;
// this.editableFlight.dep_region_name=flightData.dep_region_name;
// this.editableFlight.arr_airport=flightData.arr_airport;
// this.editableFlight.dep_iata=flightData.dep_iata;
// this.editableFlight.dep_terminal=flightData.dep_terminal;
// this.editableFlight.dep_longitude=flightData.dep_longitude;
// this.editableFlight.dep_latitude=flightData.dep_latitude;
// this.editableFlight.dep_country=flightData.dep_country;
// this.editableFlight.dep_city=flightData.dep_city;
// this.editableFlight.flight_number=flightData.flight_number;
// this.editableFlight.airline_code=flightData.airline_code;
// this.editableFlight.flight_type=flightData.flight_type;